version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: test_payment_gateway
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - my-network
    ports:
      - "5455:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin-test-payment:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5555:80"
    depends_on:
      - postgres
    networks:
      - my-network
volumes:
  pg_data:

networks:
  my-network:
    driver: bridge
